### ISSUE TITLE
Onlyfans starting to roll out DRM Protection

### ISSUE THREAD

**Issue by therizzryder** [DIGITALCRIMINALS/UltimaScraper#979]
Apparently, this will apply to recent uploads. Old content doesn't get this protection. 

Some have mentioned the regular Chrome extension no longer being able to download newer content. I'm not super-tech savvy, but...What does that mean for us?

**Comment by spiderzero3** [comment]
think i'm running into this. one model i follow stalls the scraper. it gets stuck "Processing Scraped Messages" indefinitely.

when i go into her messages to try and download it manually, i can see that the video is now streamed in chunks instead of being one easily downloaded file like before.

![chunking](https://user-images.githubusercontent.com/91495166/235323638-0d497d2f-3cb9-4b34-9004-a8103961be1a.png)

**Comment by avekifes** [comment]
Everything that OnlyFans does is designed to scam its users.

1. "Creators" allowed to scam you by selling things behind a paywall with no preview required.
2. "Creators" allowed to spam your inbox even after you've subscribed, with no global way to turn it off.
3. Now they've even implemented DLC, so users can't even download things that they technically paid for.

**Comment by Gamma-Velorum** [comment]
How Leo went from MFC being almost model hostile to actually now implementing the most member hostile change to OF is dumbfounding. I am done and no longer buying anything new but I know there will be no push back because there is no avenue or forum to organise such a thing.
